### ISSUE TITLE
Deside how is better to use hidden exams

### ISSUE THREAD

**Issue by NatShep** [NatShep/ChoTISkazal#11]
![photo_2020-11-30_22-02-29](https://user-images.githubusercontent.com/45200849/100652402-f1648480-3357-11eb-97d9-a751c1f69576.jpg)
 
twice "it's right"
one time "noo.."

how is better to use hidden exam? it doesn't clear what is "it's right" after "dont'peek"
Is it nessesary to use this exam in telegram?

**Comment by tmteam** [comment]
```

**Comment by tmteam** [comment]
```

**Comment by tmteam** [comment]
Maybe 

```
`
`
`
`
`
`
`
`
Don t peek: Previous exam was right


{text of next question}
```

**Comment by NatShep** [comment]
yea, it's better

And what about this?
.
.
.
.
.
.
.
Previous exam was right! 
Now try to answer without hints. Don't peek upward!

**Comment by tmteam** [comment]
Looks good. 

we can unite these approaches

```
.
.
.
.
.
.
.
Previous exam was right. ;)
Now try to answer without hints. Don't peek upward!

{text of next question}
```
