### ISSUE TITLE
Support russian language interface

### ISSUE THREAD

**Issue by tmteam** [NatShep/ChoTISkazal#19]
You can search for ready-made libraries in nugget/github

Basic flow:
0) Search for all strings in bot
1) Create Json file with all en-strings for bot.
3) Create same json file with all ru strings for bot
4) Add static or singletone class to support all bot strings
5) Move all strings in bot to the singletone
6) Add /interfacelang menu command

**Comment by NatShep** [comment]
Завалидировать текст.
Добавить к юзеру поле, какой выбран сейчас язык интерфейса.
По умолчанию - русский
