### ISSUE TITLE
Some exams repeat two times in a row

### ISSUE THREAD

**Issue by NatShep** [NatShep/ChoTISkazal#22]
![photo_2020-12-12_16-01-03](https://user-images.githubusercontent.com/45200849/101984616-a6216e80-3c93-11eb-80f6-6bef9f98931e.jpg)

**Comment by tmteam** [comment]
We should decide - is it a bug or a feature?

**Comment by tmteam** [comment]
added protection against absolutely identical questions in a row. What you have in the screenshot - I do not consider it a mistake
