### ISSUE TITLE
Add packs of words(by categories)

### ISSUE THREAD

**Issue by NatShep** [NatShep/ChoTISkazal#31]
- [x] архитектура
- [x] прописать сценарии 
- [x] набор частотных слов (40 наборов 0 - 4000) 
- [x] Модели 
- [x] репозитории
- [x] Тесты моделей и репозиториев
- [x] Процесс добавления слов в киты
- [x] Ui для выбора кита
- [x] Ui для выбора слова в ките
- [x] Ui когда выбрал 15 новых слов
- [x] Текстовки для китов
- [x] Текстовки для Ui
- [x] Файл словаря (глобальный, для переноса)
- [x] Файл основных переводов (для всех слов в сетах)
- [x]  Замержить базу частотных слов с основной базой бота

Файлы:
- [x] Частотные слова
- [x] Подобрать правильные переводы для первых 4000 частотных слов

Наборы:
- [x] 100 частотных слов
- [x] [100-300] частотных слов
- [x] [300-600] частотных слов
- [x] [600-1000] частотных слов
- [x] 2k частотных слов
- [x] 3k частотных слов
- [x] 4k частотных слов
- [x] 5k частотных слов

**Comment by tmteam** [comment]
Модель банча:
	- Слова в перемешанном порядке[]
		- Id слова
		- Принятые переводы []
		- id Принятых фраз []
	- Id
	- Раз выбрано
	- Раз пройдено
	- Показывается ли
	- Рекламакция: Покрывают около 50 % любого английского текста (кроме специализированной и научной литературы)

У юзера
	- Бранч[]
		- Id
		- Номер последнего слова



На морде 

________________________________
У нас есть очень много слов. За раз - несдюжишь!

Наборы слов разбиты по категориям 

Нажмите /AllSets что бы увитеть все наборы сразу (их там очень много)

Ну или выберите категорию
_______________________
[500 Самых основных слов]
[500-1000    Чучуть знаю]
[1000-2000  Что то да знаю]
[2000-3000 Знаю]
[3000-4000 удиви меня]
[Сленг]
[Интересные слова]
[Computer science]

_______________________________
Вторая сотня самых частых слов

Уровень: Новичек
[Elementary]

Изучено 25/100

[Приступить]
[Следующий набор ->]
[<- предыдущий набор]

[Главное меню]
_______________________________

Карточка слова

-----------------------------
Mother
[maza]
Мама, Мамаша, мамзель

Пример:
Your mother
Твоя мама

[Буду учить]
[Пропустить ->]
[Главное меню]
[Начать изучение]
_____________________________


Когда набрал 15 новых слов

___________________________
Вы набрали 15 новых слов - самое время начать их учить!

[Начать изучение]
[Продолжить добавление]
[Главное меню]
------------------------------------
