### ISSUE TITLE
Cannot remove word

### ISSUE THREAD

**Issue by tmteam** [NatShep/ChoTISkazal#44]
Scenario

1) Add word 'mother'
2) Remove word 'mother' (add word and deselect all translations)

Expected: 'Mother' does not appear in question
Actual: It appears ;(

**Comment by NatShep** [comment]
Предлагаю добавить еще одно поле в модель слова, которое будет отвечать за видимость в вопросах. 
Когда мы помечаем слово, как удаленное, оно больше не участвует в вопросах, но слово сохраняется в базе данных. 
Таким образом, сохраняется статистика, и если мы добавим его заново, то изучение этого слово продолжится с того, на чем мы остановились.

**Comment by tmteam** [comment]
Похоже что это было починено раньше. Добавил тесты на удаление
