### ISSUE TITLE
Small difference in answer shouldn't fail exam

### ISSUE THREAD

**Issue by NatShep** [NatShep/ChoTISkazal#9]
![photo_2020-11-30_20-33-45](https://user-images.githubusercontent.com/45200849/100644245-210d8f80-334c-11eb-8aae-5e5ab0b40f2d.jpg)

**Comment by NatShep** [comment]
add spesial comparison for words. It should retutn true If words hav minimal difference.
For example it helps tо avoid the next situation:
![photo_2020-12-12_16-01-03](https://user-images.githubusercontent.com/45200849/101984740-6d35c980-3c94-11eb-9a25-e6cfface0520.jpg)
"извлекать" "извлечь" have simalar meaning. But "извлекать" is definition for "retrieve".  "извлечь" is definiton for fetch. In fact the both of english words has the same definition.

**Comment by tmteam** [comment]
![image](https://user-images.githubusercontent.com/8751262/102399320-95148c80-4008-11eb-8ceb-abb006668e67.png)


Applied levinshtein distance for small mistakes.


You wrote
```
извлекать" "извлечь" have simalar meaning. But "извлекать" is definition for "retrieve". "извлечь" is definiton for fetch. In fact the both of english words has the same definition.
```

But it is case for vectoring and machine learning - wow, hard and not so important task

Ill create ML task for this case
